with open("audit.md", "a") as f:
    f.write("\n\n## Cross-Product Expansion & Failure Modes\n\n")
    f.write("The `DeriveKinematicsStep` is designed to deduce physical configurations dynamically. The hardware parameter space consists of:\n")
    f.write("- **Left/Right Motor Polarity:** Standard or Reversed (changes whether +PWM moves the wheel Forward or Backward).\n")
    f.write("- **Left/Right Motor Channel Mapping:** Which I2C channel maps to which physical side.\n")
    f.write("- **IMU Orientation:** The 3D orientation of the IMU relative to the robot chassis (Pitch, Yaw, Roll, and Inversion).\n\n")

    f.write("### Success Modes\n\n")
    f.write("1. **Standard Configuration (No inverts, standard mount):**\n")
    f.write("   - Phase matches. Pitch and Forward axes identified successfully. `raw_up` properly identifies Vertical.\n")
    f.write("   - **Result: SUCCESS.** Robot balances perfectly.\n\n")

    f.write("2. **Single Motor Reversed Polarity (e.g., Left Motor Backwards):**\n")
    f.write("   - `DeriveKinematicsStep` detects a phase mismatch during the pulse test and aligns the 'Normal' motor to the 'Reversed' motor. Both motors now move backward on +PWM.\n")
    f.write("   - The algorithm redefines 'Forward' as 'Backward' physically. It then incorrectly deduces that Left and Right channels are swapped relative to this new direction.\n")
    f.write("   - **Result: SUCCESS.** Pitch and Yaw senses are inverted to match the reversed motors. The robot successfully balances and steers, but the physical 'Front' becomes the logical 'Back'.\n\n")

    f.write("3. **Both Motors Reversed Polarity:**\n")
    f.write("   - Phase matches immediately (both go backwards). Pitch and Accel signals invert.\n")
    f.write("   - **Result: SUCCESS.** The robot operates perfectly, similarly redefining its 'Front' as 'Back'.\n\n")

    f.write("4. **IMU Mounted Sideways / Upside Down:**\n")
    f.write("   - `analyze_dominance` dynamically reassigns axes. The calculation of physical Up (`raw_up = glm.cross(sum_accel, sum_gyro)`) is invariant to sensor orientation because it relies on the physical cross product of Lag and Pitch.\n")
    f.write("   - **Result: SUCCESS.** Axis remapping perfectly accommodates 90-degree and 180-degree physical rotations of the IMU.\n\n")

    f.write("### Failure Mode: Phase Mismatch with Positive Feedback (The \"Spinning in a Circle\" Issue)\n\n")
    f.write("There is a specific edge-case failure mode involving the physical environment rather than the algorithm itself, which leads directly to the robot **\"spinning in a circle, but thinking it was tipping over.\"**\n\n")
    f.write("**The Catalyst:**\n")
    f.write("If the robot's wheels lack traction (e.g., slipping on a smooth surface) or the pulse power is too weak, the single-motor wiggle generates extremely low linear acceleration (`accel_delta`). If this signal falls below the noise floor or is overpowered by gravity tilt:\n")
    f.write("- `glm.dot(l_accel_delta, r_accel_delta)` may incorrectly evaluate as positive, failing to detect an actual phase mismatch.\n\n")
    f.write("**The Cascade:**\n")
    f.write("1. **Axis Contamination:** With opposing motors incorrectly considered 'matched', one motor pulses forward and the other backward. This produces pure physical **Yaw** rather than Pitch.\n")
    f.write("2. **Axis Swapping:** `sum_gyro` becomes dominated by Yaw rotation. The calibration logic mistakenly assigns the IMU's Pitch Axis to the physical Yaw axis.\n")
    f.write("3. **Positive Feedback Loop:**\n")
    f.write("   - When the robot attempts to balance, a slight physical forward tilt is mistakenly read as a Yaw error.\n")
    f.write("   - The PID controller attempts to correct this 'Yaw' by driving the wheels in opposite directions.\n")
    f.write("   - This opposing drive spins the robot in a circle physically.\n")
    f.write("4. **Centripetal False-Pitch:** As the robot spins rapidly in a circle, centripetal acceleration acts on the off-center IMU. This radial acceleration registers on the IMU as continuous Pitch (tipping), causing the robot to drive the motors harder, exacerbating the spin.\n\n")
    f.write("**Conclusion:** The observed behavior is not a logical gap in the cross-product mapping, but an environmental failure causing the initial phase-alignment to fail, leading to Pitch and Yaw axes becoming perfectly swapped in software.\n")
